# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target ‘WLCKitPodTest’ do

source 'https://git.coding.net/wanglichun/WLCSpecs.git'
pod ‘WLCKit’, '~>1.3'

end
